{
 "title": "authentik",
 "description": "Grafana Dashboard for Prometheus metrics exposed by authentik.",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "PolicyEngine Execution time by binding type",
   "type": "graph",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by(binding_target_name, binding_target_type) (rate(authentik_policies_execution_time_sum[5m]) / rate(authentik_policies_execution_time_count[5m]))"
    }
   ]
  },
  {
   "title": "PolicyEngine Execution time by binding target",
   "type": "graph",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by(object_name, object_type) (rate(authentik_policies_execution_time_sum[5m]) / rate(authentik_policies_execution_time_count[5m]))"
    }
   ]
  },
  {
   "title": "Task status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(authentik_system_tasks{status=\"TaskResultStatus.ERROR\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(authentik_system_tasks{status=\"TaskResultStatus.SUCCESSFUL\"})",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "\n\n<img src=\"https://goauthentik.io/img/icon_top_brand.svg\">"
   }
  },
  {
   "title": "Cached policies",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "authentik_policies_cached", "legendFormat": "Cached policies" },
    {
     "expr": "authentik_models{app=\"authentik_policies\", model_name=\"policy\"}",
     "legendFormat": "Total policies"
    }
   ]
  },
  {
   "title": "Connected Workers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(authentik_admin_workers)" }
   ]
  },
  {
   "title": "System task duration",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (task_name) (authentik_system_tasks)"
    }
   ]
  },
  {
   "title": "FlowPlanner time by flow",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (flow_slug) (rate(authentik_flows_plan_time_sum[5m]) / rate(authentik_flows_plan_time_count[5m]))"
    }
   ]
  }
 ]
}