{
 "title": "CouchDB Dashboard",
 "description": "CouchDB Dashboard ",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node_name", "query": "couchdb_httpd_node_up" },
   { "name": "method", "query": "couchdb_httpd_request_methods" }
  ]
 },
 "panels": [
  {
   "title": "Number of CouchDB Nodes Available",
   "type": "singlestat",
   "description": "Number of CouchDB Nodes Available",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(couchdb_httpd_node_up{node_name=\"$node_name\"}[5m])"
    }
   ]
  },
  {
   "title": "Total number of databases in the cluster",
   "type": "singlestat",
   "description": "Total number of databases in the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(couchdb_httpd_databases_total[5m])"
    }
   ]
  },
  {
   "title": "CouchDB HTTPD Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(couchdb_httpd_requests{node_name=\"$node_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "CouchDB HTTP Request per Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(couchdb_httpd_request_methods{method=\"$method\",node_name=\"$node_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "CouchDB Open OS Files",
   "type": "graph",
   "description": "number of file descriptors CouchDB has open",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(couchdb_httpd_open_os_files{node_name=\"$node_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "CouchDB number of clients for continuous changes",
   "type": "graph",
   "description": "number of clients for continuous _changes",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "avg(rate(couchdb_httpd_clients_requesting_changes{node_name=\"$node_name\"}[5m]))"
    }
   ]
  }
 ]
}