{
 "title": "Loki / Stack Monitoring",
 "description": "This dashboard can be used to detect issues on the Loki stack, when deployed in Kubernetes. \n\nShows: \n- some error metrics published by Loki\n- error and warning logs emitted by Loki and Fluent Bit\n- memory and CPU usage of Loki and Fluent Bit compared against the Kubernetes memory/cpu limits and requests",
 "tags": [
  "tools",
  "loki"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Summary of alerts status", "type": "alertlist", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 } },
  { "title": "Problems in the Loki Stack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Number of error/warning messages logged by Loki itself",
   "type": "graph",
   "description": "Total number of messages logged by Loki itself",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(log_messages_total{app=\"loki\",level=~\"error|warn\"}[1m])) by (level)\n",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Loki itself",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"fluent-bit\",namespace=\"observability\",pod=~\"loki.*\"} |~ \"(?i)(warn|error)\""
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Fluent Bit",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"fluent-bit\",namespace=\"observability\",pod=~\"fluent-bit.*\"} |~ \"(?i)(warn|error)\""
    }
   ]
  },
  {
   "title": "Loki (distributor) - failed batch appends sent to ingesters",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_distributor_ingester_append_failures_total[1m])*60"
    }
   ]
  },
  { "title": "Logging activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Number of Streams in Loki",
   "type": "graph",
   "description": "The total number of streams created per tenant.\nThis should not increase after startup.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "loki_ingester_memory_streams", "legendFormat": "Streams" }
   ]
  },
  {
   "title": "Loki (distributor) - log entries received per second",
   "type": "graph",
   "description": "The total number of log entries received per tenant (not necessarily of lines, as an entry can have more than one line of text).",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_distributor_lines_received_total[1m])"
    }
   ]
  },
  {
   "title": "Bytes received in ingester per second",
   "type": "graph",
   "description": "The total number of uncompressed bytes received per tenant.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[1m]))"
    }
   ]
  },
  { "title": "Memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Loki memory usage (% of Kubernetes memory limit)",
   "type": "graph",
   "description": "Percentage of actual usage over configured limit",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * container_memory_working_set_bytes{container=\"app\",pod=~\"loki.*\"}\n/\non (pod,container) (kube_pod_container_resource_limits{container=\"app\",pod=~\"loki.*\",resource=\"memory\",unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Loki memory usage vs Kubernetes limit and request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container!=\"\",container!=\"POD\",pod=~\"loki.*\"}",
     "legendFormat": "Usage (pod={{pod}}, container={{container}})"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{pod=~\"loki.*\",resource=\"memory\",unit=\"byte\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{pod=~\"loki.*\",resource=\"memory\",unit=\"byte\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Fluent Bit memory usage (% of Kubernetes memory limit)",
   "type": "graph",
   "description": "Percentage of actual usage over configured limit",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100* container_memory_working_set_bytes{container=\"fluent-bit\",pod=~\"fluent-bit.*\"}\n/\non (pod,container) (kube_pod_container_resource_limits{container=\"fluent-bit\",pod=~\"fluent-bit.*\",resource=\"memory\",unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Fluent Bit memory usage vs Kubernetes limit and request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container!=\"\",container!=\"POD\",pod=~\"fluent-bit.*\"}",
     "legendFormat": "Usage (pod={{pod}}, container={{container}})"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{pod=~\"fluent-bit.*\",resource=\"memory\",unit=\"byte\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{pod=~\"fluent-bit.*\",resource=\"memory\",unit=\"byte\"})",
     "legendFormat": "Request"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Loki CPU usage (% of Kubernetes CPU request)",
   "type": "graph",
   "description": "percentage of configured limit",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "percent", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "100* rate(container_cpu_usage_seconds_total{container=\"app\",pod=~\"loki.*\"}[1m])\n/\non (pod,container) kube_pod_container_resource_requests{container=\"app\",pod=~\"loki.*\",resource=\"cpu\",unit=\"core\"}"
    }
   ]
  },
  {
   "title": "Loki CPU usage vs Kubernetes limit and request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",pod=~\"loki.*\"}[1m])",
     "legendFormat": "CPU Usage (pod={{pod}}, container={{container}})"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{pod=~\"loki.*\",resource=\"cpu\",unit=\"core\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{pod=~\"loki.*\",resource=\"cpu\",unit=\"core\"})",
     "legendFormat": "CPU Request"
    }
   ]
  },
  {
   "title": "Fluent Bit CPU usage (% of Kubernetes CPU request)",
   "type": "graph",
   "description": "percentage of configured limit",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "percent", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "100 * rate(container_cpu_usage_seconds_total{container=\"fluent-bit\",pod=~\"fluent-bit.*\"}[1m])\n/\non (pod,container) kube_pod_container_resource_requests{container=\"fluent-bit\",pod=~\"fluent-bit.*\",resource=\"cpu\",unit=\"core\"}"
    }
   ]
  },
  {
   "title": "Fluent Bit CPU usage vs Kubernetes limit and request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",pod=~\"fluent-bit.*\"}[1m])",
     "legendFormat": "CPU Usage (pod={{pod}}, container={{container}})"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{pod=~\"fluent-bit.*\",resource=\"cpu\",unit=\"core\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{pod=~\"fluent-bit.*\",resource=\"cpu\",unit=\"core\"})",
     "legendFormat": "CPU Request"
    }
   ]
  }
 ]
}